% IsSuccessful = szy_PoissonReconstruction(in_xyz_file_name, min_angle, ...
%    max_triangle_radius_over_average_spacing, approximation_distance_over_average_spacing, ...
%    out_file_name)
% min_angle: min triangle angle in degrees.
% max_triangle_radius_over_average_spacing: recommend at least 100 
% approximation_distance_over_average_spacing: recommend at least 0.25
% Poisson重构，效果没有Screened Poisson重构好，但是能够保证重构出来的模型是二维流形。
function IsSuccessful = szy_PoissonReconstruction(in_xyz_file_name, min_angle, ...
    max_triangle_radius_over_average_spacing, approximation_distance_over_average_spacing, ...
    out_file_name)

[status,~] = dos(['szy_PoissonReconstruction.exe "', in_xyz_file_name, '" ', ...
    int2str(min_angle), ' ', num2str(max_triangle_radius_over_average_spacing), ' ', ...
    num2str(approximation_distance_over_average_spacing), ' "', out_file_name, '"'], '-echo');

IsSuccessful = (status == 0);
end